In [1]:
import torch

torch.__version__

'2.5.1+cu121'

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.4720, 0.7641, 0.8364, 0.1184],
         [0.1744, 0.2342, 0.1532, 0.8940],
         [0.9346, 0.2020, 0.5619, 0.1082]]),
 torch.float32)

In [15]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))

random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [16]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [17]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype, ones.ndim

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32,
 2)

In [18]:
# Create a range of values 0 to 10.

zero_to_ten = torch.arange(0, 10, 2)
zero_to_ten

tensor([0, 2, 4, 6, 8])

In [19]:
# Create a tensor
some_tensor = torch.rand(size=(3, 4))

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.8689, 0.2097, 0.0650, 0.0189],
        [0.5846, 0.7591, 0.7806, 0.4768],
        [0.1574, 0.9929, 0.2606, 0.8438]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [20]:
tensor = torch.tensor([1, 2, 3])

tensor + 10

tensor([11, 12, 13])

In [21]:
tensor * 10

tensor([10, 20, 30])

In [22]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [23]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [24]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [25]:
print( tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [26]:
import torch

tensor = torch.tensor([1, 2, 3])

tensor.shape

torch.Size([3])

In [27]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [28]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [29]:
tensor @ tensor

tensor(14)

In [30]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype = torch.float32)
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)


In [31]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [32]:
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [33]:
output_1 = tensor_A @ tensor_B.T
output_1

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [34]:
output_2 = torch.matmul(tensor_A, tensor_B.T)
output_2

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [35]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [36]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=2, out_features=6)

x = tensor_A
output = linear(x)

print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [37]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [39]:
x
print(f"Tensor: {x}")

print(f"Index where max value occurs: {x.argmax()}")
print(f"Index where min value occurs: {x.argmin()}")

Tensor: tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 9
Index where min value occurs: 0


In [40]:
tensor = torch.arange(1, 100, 5)
tensor.dtype

torch.int64

In [41]:
tensor_float32 = tensor.type(torch.float32)
tensor_float32, tensor_float32.dtype

(tensor([ 1.,  6., 11., 16., 21., 26., 31., 36., 41., 46., 51., 56., 61., 66.,
         71., 76., 81., 86., 91., 96.]),
 torch.float32)

In [42]:
x = torch.arange(1.0, 8., 1.0)
x, x.shape, x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]), 1)

In [43]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]), 2)

In [44]:
z = x.view(1, 7)
z, z.shape, z.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]), 2)

In [45]:
z[:, 6] = 5
z, x

(tensor([[1., 2., 3., 4., 5., 6., 5.]]), tensor([1., 2., 3., 4., 5., 6., 5.]))

In [46]:
x_stacked_0 = torch.stack([x, x, x, x], dim=0)
x_stacked_1 = torch.stack([x, x, x, x], dim=1)

x_stacked_0, x_stacked_0.ndim, x_stacked_0.shape, x_stacked_1, x_stacked_1.ndim

(tensor([[1., 2., 3., 4., 5., 6., 5.],
         [1., 2., 3., 4., 5., 6., 5.],
         [1., 2., 3., 4., 5., 6., 5.],
         [1., 2., 3., 4., 5., 6., 5.]]),
 2,
 torch.Size([4, 7]),
 tensor([[1., 1., 1., 1.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [5., 5., 5., 5.]]),
 2)

In [47]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 5.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([1., 2., 3., 4., 5., 6., 5.])
New shape: torch.Size([7])


In [48]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")
print(f"Previous dim: {x_squeezed.ndim}")
## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)

print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")
print(f"New dim: {x_unsqueezed.ndim}")

Previous tensor: tensor([1., 2., 3., 4., 5., 6., 5.])
Previous shape: torch.Size([7])
Previous dim: 1

New tensor: tensor([[1., 2., 3., 4., 5., 6., 5.]])
New shape: torch.Size([1, 7])
New dim: 2


In [49]:
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(0, 2, 1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([224, 3, 224])


In [50]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [51]:
print(f"First square bracket: \n{x[0]}")
print(f"Second square bracket: \n{x[0][0]}")
print(f"Third square bracket: \n{x[0][0][0]}")

First square bracket: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: 
tensor([1, 2, 3])
Third square bracket: 
1


In [52]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [53]:
# Get all values of 0th dimension and the 2 index of 1st dimension
x[:, 2]

tensor([[7, 8, 9]])

In [54]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [55]:
# Get all values of 0th & 1st dimensions but only index 2 of 2nd dimension
x[:, :, 2]

tensor([[3, 6, 9]])

In [56]:
# Get index 0 of 0th and 1st dimensions and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [57]:
random_tensor_A = torch.rand(size=(3, 4))
random_tensor_B = torch.rand(3, 4)
print(f"Tensor A: \n{random_tensor_A}\n")
print(f"Tensor B: \n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A: 
tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])

Tensor B: 
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [58]:
import random

RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C: \n{random_tensor_C}\n")
print(f"Tensor D: \n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C: 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D: 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [59]:
torch.cuda.is_available()

False

In [60]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [61]:
torch.cuda.device_count()

0

In [62]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu


tensor([1, 2, 3]) cpu


tensor([1, 2, 3])

In [63]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [64]:
tensor_on_gpu

tensor([1, 2, 3])